### ISSUE TITLE
Code Lab Feedback

### ISSUE THREAD

**Issue by KatieMFritz** [KatieMFritz/codelab-rails-database-intro#2]
Hey @chrisvfritz, can you take a look at this? It's [hosted here](https://sheltered-falls-6096.herokuapp.com) and meets the following [project](http://lansingcodelab.com/lessons/rails-database-intro/1) criteria:
- [x] you've generated a scaffold for a model (other than Post) - [check this list](https://gist.github.com/chrisvfritz/bfdae85cb78f654626bd) if you need ideas
- [x] your model has at least 3 attributes, of at least 3 separate data types
- [x] every column for your model's table uses `null: false` and/or `default: ...` where and only where appropriate
- [x] the `index` action for your model is linked to from a homepage in a `static` controller
- [x] the homepage has information describing what the webapp is for
- [x] every attribute on the model is visible and clearly labeled on the views for the `index` and `show` actions
- [x] every attribute on the model is editable through the `new`/`create` and `edit`/`update` actions

**Comment by KatieMFritz** [comment]
Did I do this right?

**Comment by chrisvfritz** [comment]
- You don't actually need [the `null: true` here](https://github.com/KatieMFritz/codelab-rails-database-intro/blob/master/db/migrate/20151216212807_create_books.rb#L5), as that's the default.
- Will there ever be a situation where you want to save a book with a blank title to the database? Are you sure you want a default for `title`?
- Try using a `link_to` helper with a path helper [to link to the books page here](https://github.com/KatieMFritz/codelab-rails-database-intro/blob/master/app/views/static/home.html.erb#L3).

**Comment by KatieMFritz** [comment]
Okay, I think I addressed all that.

**Comment by chrisvfritz** [comment]
:+1: :shipit:
